version: '3'
services:

  db-accounts:
    image: mongo:4.2.8
    container_name: db-accounts
    ports:
      - "4001:27017"
    restart: "always"

  db-characters:
    image: mongo:4.2.8
    container_name: db-characters
    ports:
      - "4002:27017"
    restart: "always"

  federation-gateway:
    image: federation-gateway
    build:
      context: ./GraphGateway
      dockerfile: DockerfileDEV
    container_name: federation-gateway
    volumes:
      - /tmp/federation-gateway/npm-cache:/root/.npm:z
      - ./GraphGateway/src:/usr/src/app/src:z
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - ACCOUNTS_URL=http://accounts-service:80
      - CHARACTERS_URL=http://characters-service:80
    restart: "no"

  accounts-service:
    image: accounts-service
    build:
      context: ./AccountsService
      dockerfile: DockerfileDEV
    container_name: accounts-service
    volumes:
      - /tmp/accounts-service/npm-cache:/root/.npm:z
      - ./AccountsService/src:/usr/src/app/src:z
    ports:
      - "3001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db-accounts:27017
      - DBNAME=accounts-db
      - ENCRYPT_SALT=1d0jjf1030j12s18r1yg31o8ng86sm5o
      - ENCRYPT_KEY=SUPERSECRETKEY
    restart: "no"

  characters-service:
    image: characters-service
    build:
      context: ./CharactersService
      dockerfile: DockerfileDEV
    container_name: characters-service
    volumes:
      - /tmp/characters-service/npm-cache:/root/.npm:z
      - ./CharactersService/src:/usr/src/app/src:z
    ports:
      - "3002:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DBHOST=mongodb://db-characters:27017
      - DBNAME=characters-db
    restart: "no"
