import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>GraphQL MicroServices Project</h1>

        <Link href="/accounts/login">
          <a>Login</a>
        </Link>

        <br />

        <Link href="/accounts/register">
          <a>Register</a>
        </Link>

        <br />

        <Link href="/accounts/profile">
          <a>Profile</a>
        </Link>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
