import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 role="heading">GraphQL MicroServices Project</h1>

        <Link href="/accounts/login">
          <a role="login-link">Login</a>
        </Link>

        <br />

        <Link href="/accounts/register">
          <a role="register-link">Register</a>
        </Link>

        <br />

        <Link href="/accounts/profile">
          <a role="profile-link">Profile</a>
        </Link>
      </main>

      <footer className={styles.footer}>&nbsp;</footer>
    </div>
  )
}
